### PR TITLE
Added a sensible error to be thrown when config is not found.

### PR DESCRIPTION
**Pull request by ivanr3**
1. Added a sensible error message when configuration is not found
2. Updated all configuration services to use the same abstract service, so this fix is propagated across all of the tools

### CODE REVIEW

**Comment by ivanr3** [comment]
Hey @EricMcEvoyR3.
* flows-transport is a separate cordapp that requires configuration (hence the service is there)
* As of Corda v2 (as far as I remember) all service have to take `AppServiceHub` as the only constructor parameter. `ServiceHub` is still supported for api compatibility but it's deprecated.  
* TC runs builds against all PRs. In fact, I won't be able to merge my changes in until the build has passed :)

**Comment by mattbradburyuk** [comment]
Mostly makes sense apart from: why does BNOConfigurationService have a method bnoName() which overrides bnoName() in the abstract class. Doesn't that mean that whenever the method is called in the billing app it will throw an error saying don't use this method? If that's the intention, why don't you want that method used?

**Comment by ivanr3** [comment]
@mattbradburyuk  good point. So `bnoName` and `notaryName` are exposed to the abstract class because most of the services need either one or the other or both. In some cases, when one of those is not required by design, I thought that would be good to show explicitly that this method should *not* be used.

**Comment by mattbradburyuk** [comment]
Okay, so it just happens that bnoName, is not needed in the Billing app.

**Pull request merged**
